### ISSUE TITLE
hit flags seems more approriate for a global variable

### ISSUE THREAD

**Issue by hmaarrfk** [HenryHar/BTS#2]
https://github.com/HenryHar/BTS/blob/a9f2941f378a79c22603aa847f40a1196fedfc4a/streak_counter.py#L37

Seems like you use hitflags quite a bit, it seems more appropriate for a global variable (ie. a constant outside the functions).

**Comment by henryhank7** [comment]
Thank you for the suggestion Mark! I just resolved this issue and pushed it.
